spring:
  datasource:
    url: jdbc:mysql://localhost:3306/gestionstock?createDatabaseIfNotExist=true&userSSL=false&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password:
    driver-class-name: com.mysql.jdbc.Driver
  ## Specify DBMS
  jpa:
    database: MYSQL
    show-sql: false
    properties:
      hibernate:
        session_factory:
          interceptor: com.stock.gestionstock.interceptor.Interceptor
      ddl-auto: create
      dialect: org.hibernate.dialect.MySQL5Dialect

server:
  port: 8081


flickr:
  apikey: 33c4da5bdecea1255a5ec2291237317f
  apisecret: 0652d6f74510f3f3